name: Scheduled Message

on:
  schedule:
  # 0-59/10 代表每 10 分鐘，1-7 代表 UTC 的 1 點到 7 點 (即台灣 9 點到 15 點)
    - cron: '*/10 1-15 * * *'
    # 每天台灣時間早上 09:00 執行 (UTC 01:00)
   # - cron: '0 1 * * *'
  # 允許你手動按鈕觸發測試
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests
    # --- 關鍵步驟：在這裡安裝套件 ---
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # ----------------------------

      - name: Run script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python send_msg.py
